// Generated by gencpp from file hog_haar_person_detection/Pedestrians.msg
// DO NOT EDIT!


#ifndef HOG_HAAR_PERSON_DETECTION_MESSAGE_PEDESTRIANS_H
#define HOG_HAAR_PERSON_DETECTION_MESSAGE_PEDESTRIANS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <hog_haar_person_detection/BoundingBox.h>

namespace hog_haar_person_detection
{
template <class ContainerAllocator>
struct Pedestrians_
{
  typedef Pedestrians_<ContainerAllocator> Type;

  Pedestrians_()
    : header()
    , pedestrians()  {
    }
  Pedestrians_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pedestrians(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> >::other >  _pedestrians_type;
  _pedestrians_type pedestrians;




  typedef boost::shared_ptr< ::hog_haar_person_detection::Pedestrians_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hog_haar_person_detection::Pedestrians_<ContainerAllocator> const> ConstPtr;

}; // struct Pedestrians_

typedef ::hog_haar_person_detection::Pedestrians_<std::allocator<void> > Pedestrians;

typedef boost::shared_ptr< ::hog_haar_person_detection::Pedestrians > PedestriansPtr;
typedef boost::shared_ptr< ::hog_haar_person_detection::Pedestrians const> PedestriansConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hog_haar_person_detection::Pedestrians_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hog_haar_person_detection::Pedestrians_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hog_haar_person_detection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'hog_haar_person_detection': ['/home/thinkpad/catkin_ws/src/hog_haar_person_detection/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hog_haar_person_detection::Pedestrians_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hog_haar_person_detection::Pedestrians_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hog_haar_person_detection::Pedestrians_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hog_haar_person_detection::Pedestrians_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hog_haar_person_detection::Pedestrians_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hog_haar_person_detection::Pedestrians_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hog_haar_person_detection::Pedestrians_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa953661beff944b160295ead7064755";
  }

  static const char* value(const ::hog_haar_person_detection::Pedestrians_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa953661beff944bULL;
  static const uint64_t static_value2 = 0x160295ead7064755ULL;
};

template<class ContainerAllocator>
struct DataType< ::hog_haar_person_detection::Pedestrians_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hog_haar_person_detection/Pedestrians";
  }

  static const char* value(const ::hog_haar_person_detection::Pedestrians_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hog_haar_person_detection::Pedestrians_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
hog_haar_person_detection/BoundingBox[] pedestrians\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: hog_haar_person_detection/BoundingBox\n\
geometry_msgs/Point center\n\
uint32 width\n\
uint32 height\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::hog_haar_person_detection::Pedestrians_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hog_haar_person_detection::Pedestrians_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pedestrians);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Pedestrians_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hog_haar_person_detection::Pedestrians_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hog_haar_person_detection::Pedestrians_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pedestrians[]" << std::endl;
    for (size_t i = 0; i < v.pedestrians.size(); ++i)
    {
      s << indent << "  pedestrians[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hog_haar_person_detection::BoundingBox_<ContainerAllocator> >::stream(s, indent + "    ", v.pedestrians[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOG_HAAR_PERSON_DETECTION_MESSAGE_PEDESTRIANS_H
